gun=rocket              //sprite
inaccuracyArc=5     //level of inaccurancy +- in degrees
bulletNum=3             //number of bullets to fire at once
bulletArc=35            //Arc in which to spread bullets in bulletNum
bulletString=3      //number of bullets in a string
bulletStringN=0     //counter variable for bulletString
bulletStringCD=1    //frames between each bullet in the string
rof=ceil(room_speed)  //cooldown timer
recoil=15               //recoil amount STATIC defined by gun
