gun=sniper          //sprite
bulletNum=1         //number of bullets to fire at once
bulletString=5      //number of bullets in a string
bulletStringN=0     //counter variable for bulletString
bulletStringCD=2    //frames between each bullet in the string
rof=room_speed      //cooldown timer
laser_sight=true    //display lazer sight
disableInput=true   //does shooting diable input
recoil=0            //recoil amount STATIC defined by gun
